---
- name: "GitOps SQL Master Playbook"
  hosts: all
  become: yes
  vars_files:
    - databases.yml

  tasks:
    # --- 1. SPRACOVANIE db_list (present/absent) ---
    - name: "Správa databáz podľa stavu (db_list)"
      community.mysql.mysql_db:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        login_user: root
        login_password: root
        login_host: "localhost"
      loop: "{{ db_list }}"
      # Pri Galere stačí na jednom node, pri MySQL (bez klastra) na všetkých
      run_once: "{{ 'mariadb_galera' in group_names }}"

    # --- 2. SPRACOVANIE databases_to_create (len present) ---
    - name: "Hromadné vytvorenie nových databáz"
      community.mysql.mysql_db:
        name: "{{ item }}"
        state: present
        login_user: root
        login_password: root
        login_host: "localhost"
      loop: "{{ databases_to_create }}"
      run_once: "{{ 'mariadb_galera' in group_names }}"
