---
- name: "GitOps Správa SQL Klastrov"
  hosts: all
  become: yes
  vars_files:
    - databases.yml  # Načíta zoznam databáz zo súboru

  tasks:
    # --- LOGIKA PRE MARIADB GALERA (IP 172.18.0.x) ---
    - name: "Vytvorenie DB v MariaDB klastri"
      mysql_db:
        name: "{{ item }}"
        state: present
        login_user: root
        login_password: root
      loop: "{{ databases_to_create }}"
      when: "'mariadb_galera' in group_names"
      run_once: true

    # --- LOGIKA PRE MYSQL INNODB (IP 172.17.0.x) ---
    - name: "Vytvorenie DB v MySQL klastri"
      mysql_db:
        name: "{{ item }}"
        state: present
        login_user: root
        login_password: root
      loop: "{{ databases_to_create }}"
      when: "'mysql_innodb' in group_names"
